### ISSUE TITLE
Provide OPENCV version and Visual Studio version info in README.MD

### ISSUE THREAD

**Issue by abinashdash17** [Li-Zhaoxi/AAMED#1]
I'm unable to compile the program in Codeblocks. I think the problem is regarding OCV version i'm using in CODEblocks

**Comment by Li-Zhaoxi** [comment]
I will update the required files in these days.

We use OpenCV 3.1.0 and VS 2015. 
The original main.cpp has some mistakes. You can replace **int  main()** with the following code.

int main()
{
	string imgPath = "002_0038.jpg";
	Mat imgC, imgG;
	FLED aamed(540, 960); 
	aamed.SetParameters(CV_PI / 3, 3.4, 0.77);
	imgC = cv::imread(imgPath);
	cv::cvtColor(imgC, imgG, CV_RGB2GRAY);
	aamed.run_FLED(imgG);
	cv::Vec<double, 10> detailTime;
	aamed.showDetailBreakdown(detailTime);
	aamed.drawFLED(imgG, "res.jpg");
	cv::waitKey();
	return 0;
}

**Comment by abinashdash17** [comment]
I'll try that out.

**Comment by abinashdash17** [comment]
Thanx. Its working with some minor modifications. i.e In pragma section non-ascii characters has to be replaced with ascii chars. I'll create an issue for this minor problem. Please provide a fix for it. Nevrtheless, it worked with the modified main function. I'll close the issue.
