### ISSUE TITLE
We face the following errors while executing the setup.m program using MATLAB R2019b. Kindly suggest how to solve these issues 

### ISSUE THREAD

**Issue by Pradeep391** [Li-Zhaoxi/AAMED#2]
Building with 'MinGW64 Compiler (C++)'.
Error using mex
Cannot export mexFunction: symbol not defined
C:\Users\NITR\AppData\Local\Temp\mex_154556940944356_3936\mexElliFit.obj:mexElliFit.cpp:(.text+0x998):
undefined reference to `cv::Mat::t() const'
C:\Users\NITR\AppData\Local\Temp\mex_154556940944356_3936\mexElliFit.obj:mexElliFit.cpp:(.text+0x9ad):
undefined reference to `cv::Mat::inv(int) const'

**Comment by Li-Zhaoxi** [comment]
These errors mean that you might not used enough libraries. 

Do you use the OpenCV libraries that are compiled by MinGW?
If not, you might need to compiled OpenCV from source codes.

If your OpenCV does not contain opencv_world, you can try to use -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_flann to compile mexElliFit.cpp.

**Comment by Pradeep391** [comment]
Thanks for your positive response, which helps me to solve this issue.
