### ISSUE TITLE
Sir, kindly suggest "how to solve the following issues"

### ISSUE THREAD

**Issue by Pradeep391** [Li-Zhaoxi/AAMED#3]
We have successfully created mexElliFit.mexw64 from mexElliFit.cpp file. The mexElliFit.mexw64 is placed in the same location, where text_ellifit.m is stored. However, while executing text_ellifit.m program, the following error occurs. 

Invalid MEX-file 'F:\LAPTOP\AAMED-master\labeltool\mexElliFit.mexw64': The specified module could not be found.

Error in test_ellifit (line 9)
res = mexElliFit([x(:),y(:)]);

**Comment by Li-Zhaoxi** [comment]
Em....., I guess you may not put the shared libraries of OpenCV into the environment variable.

You can add your OpenCV library directory into LD_LIBRARY_PATH (Ubuntu) or PATH (Windows).

**Comment by Pradeep391** [comment]
Thanks for your response. It helps me to solve this issues.
