### ISSUE TITLE
python comlipe error

### ISSUE THREAD

**Issue by B1gBattery** [Li-Zhaoxi/AAMED#4]
Cannot open source file: '..\src\AAMBasedCombinations.cpp': No such file or directory

when i look into the file and find no AAMBasedCombinations.cpp indeed,is there something missing?

**Comment by Li-Zhaoxi** [comment]
"AAMBasedCombinations.cpp" is useless in AAMED, and has been deleted.

I have fix the bugs of compiling AAMED for python, you can upgrade this repository.

Also，you can delete the code  "..\src\AAMBasedCombinations.cpp" in setup.py , and supplement the code as follows before 'void drawAAMED(unsigned char* _img_G, int irows, int icols, cv::Vec3b *_outImg)' in FLED.h

	void drawAAMED(unsigned char* _img_G, int irows, int icols)
	{
		Mat img_G = Mat(irows, icols, CV_8UC1, _img_G).clone();
		cvtColor(img_G, img_G, cv::COLOR_GRAY2BGR);
		drawFLED(img_G, 0);
		cv::waitKey(0);
	}

Then, you can compile AAMED successfully.

**Comment by B1gBattery** [comment]
i made it  ,many thanks

**Comment by wantsjean** [comment]
hi, I met the same error on debian 9, when I removed "..\src\AAMBasedCombinations.cpp", it shows 
```
gcc: error: ..\src\Contours.cpp: No such file or directory
gcc: error: /TP: No such file or directory
```

**Comment by wantsjean** [comment]
oh, I forgot to replace the \\ with / , and I remove /TP，then it works, thanks!
