### ISSUE TITLE
possible bug of Get_del_phi_max???

### ISSUE THREAD

**Issue by xiahaa** [Li-Zhaoxi/AAMED#5]
Hi, Thanks a lot for open sourcing your great work.
I am here to report a possible bug of Get_del_phi_max function.
I have read the paper "A Parameter Independent Line Fitting Method".
In your code of this function: Get_del_phi_max
> 	return max_del_phi / s_pow_2;

Should this be `return max_del_phi / s_pow_3;`?
It is also ok to use `return max_del_phi / s_pow_2;`, but when you do the condition test `if (dMax > dTol*s && pMax != 0)`, there is no need to multiply `s`. 

This is my understanding of the paper "A Parameter Independent Line Fitting Method" and your implementation.

Looking forward to hear from you.

**Comment by Li-Zhaoxi** [comment]
@xiahaa  I'm glad that you are interested in our work.

In that paper, d_tol = s*delta_phi_max, delta_phi_max = max(A(|s^2-sB+B^2|)/s^3), the condition in Step 3 is (d_max <= d_tol).

In my code,
```
del_phi = A * (pow(s, 2) - s * B + pow(B, 2)) / pow(s, 3);
lst_del_phi[n - 1] = del_phi;
d_tol = s*max(lst_del_phi);
```
the condition in Step is `(dMax > dTol && pMax != 0)`

I didn't find any codes that didn't match that paper or its original C# code.

Could you point it out more clearly? Thank you.

**Comment by xiahaa** [comment]
```
static inline double Get_del_phi_max(double s, double phi)
{
	const int num_del_phi = 8;
	const double cos_phi = cos(phi), sin_phi = sin(phi);
	const double s_pow_2 = pow(s, 2), s_pow_3 = pow(s, 3);	
	double A[num_del_phi], B[num_del_phi];
	double lst_del_phi[num_del_phi], del_phi, max_del_phi(-1);

	A[0] = fabs(sin_phi + cos_phi), A[1] = fabs(sin_phi - cos_phi);
	A[2] = A[4] = A[6] = A[0], A[3] = A[5] = A[7] = A[1];
	B[0] = B[1] = cos_phi + sin_phi;
	B[2] = B[3] = -cos_phi + sin_phi;
	B[4] = B[5] = cos_phi - sin_phi;
	B[6] = B[7] = -cos_phi - sin_phi;
	for (int n = 0; n < num_del_phi; n++)
	{
		del_phi = A[n] * (s_pow_2 - s * B[n] + pow(B[n], 2));
		//del_phi = A[n] * (s_pow_2 + B[n] * (B[n] - s));
		//del_phi = A[n] * (pow(B[n] - s, 2) - s * B[n]);
		if (del_phi > max_del_phi)
			max_del_phi = del_phi;
	}

	return max_del_phi / s_pow_2;// here is my concern
}
```

**Comment by Li-Zhaoxi** [comment]
@xiahaa  Yes, you are right! 

Fortunately, this bug doesn't have a big impact on the detection performance. I will fix this bug in my future work. 

Thanks a lot! :smile:

**Comment by xiahaa** [comment]
Hi, it's me again. Sorry~

I have another concern about the implementation of the following two functions:
`sortCombine(fitComb_LR, search_arcMats, search_group);`

and

`BiDirectionVerification(fitComb_LR, search_arcMats, search_group, _arc_grouped_label);`

In `sortCombine`, the following lines choose to combine one posterior arc and one anterior arc:
```
for (int i = 0; i < linking_num; i++) //r
	{
		val_r = arcMats[0][i][MAT_NUMBER - 1];// the last value is actually the number of pixels in the arc
		idx_i = i*linked_num;
		for (int j = 0; j < linked_num; j++)
		{
			if (s_group[1][j].size() >= 2)
			{
				val_l = arcMats[1][j][MAT_NUMBER - 1];
				fitComb[idx_i + j]->idx_r = i;
				fitComb[idx_i + j]->idx_l = j;
				fitComb[idx_i + j]->val = val_l + val_r;
			}
			else
			{
				fitComb[idx_i + j]->val = -1;
				temp_pos++;
			}
		}
	}
```

However, it seems that there is a duplicated summation.
For example,
assume the posterior arc includes arcs 1,2,3; and the anterior arc includes 1, 25.
then perform  ` val_l + val_r` will count the length of arc 1 twice, **Right??**

This also applies to this line `fitres = FittingConstraint(fitMats[0][idx_r].val, fitMats[1][idx_l].val, fitelpres);`.
fitMats[0] is the summation matrix of fitMat of 1,2,3
fitMats[1] is the summation matrix of fitMat of 1,25.
Again, a duplication of the relevant data of arc 1.

Sorry, I figure out your solution. This is solved.
