### ISSUE TITLE
Ellipse size variable?

### ISSUE THREAD

**Issue by antithing** [Li-Zhaoxi/AAMED#9]
Hi, thank you for making this code available. i have it running very well on my images, however i notice that smaller ellipses are not found. Is there a variable set somewhere that filters ellipses by size?

Thanks

**Comment by Li-Zhaoxi** [comment]
I am glad that you are interested in our work.

Our method cannot detect small ellipse effectively.  More small ellipses mean more false results. Actually, many methods using the edge-link-based framework are not suitable for detecting small ellipses.  If your datasets contain many small ellipses, I suggest you can try [ELSD.](https://github.com/GYZHikari/ELSD). 

From the perspective of specific applications, small ellipses can be regarded as circles. You can use some low-lever vision strategies like color or region grown to obtain your circles of interest.

**Comment by antithing** [comment]
understood, thank you!
